### ISSUE TITLE
images from server

### ISSUE THREAD

**Issue by simrankathuria** [anchitgupt/Stories#2]
I have used this library but images are from server so it take some time to load image how to stop progress till the image load and start after the image is successfully loaded?

**Comment by anchitgupt** [comment]
Use libraries like glide, when some come to the activity where stories are present fetch a low-end image of the stories and when clicked on story show that low-end image until in the background the image is not fully fetched.
I hope this works, this has nothing to link to this but if you implemented you can share here,
